import java.util.*;
import java.awt.*;
import javax.swing.*;


public class PaginaUsuario extends javax.swing.JFrame {
    ArrayList <String> datosUsuario;
    String idUsuario="";
    ImageIcon fotoUsuario;
    Icon icon;
    /**
     * Creates new form PaginaUsuario
     */
    public PaginaUsuario(String usuario, Object datos) {
    
    //  public PaginaUsuario(String usuario) {
        super("Twitter");
        System.out.println("llegada exitosa");
        
        this.idUsuario=usuario;
        datosUsuario=(ArrayList)datos;
        //icon = new ImageIcon(fotoUsuario.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        
        fotoUsuario=new ImageIcon(""+datosUsuario.get(1));
        
        initComponents();
        defineComponents();//le da los valores a los componentos graficos de la BD
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jPencabezado = new javax.swing.JPanel();
        jBatras = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jLNoTweets = new javax.swing.JLabel();
        jPcentro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLNombre1 = new javax.swing.JLabel();
        jBsiguiendo = new javax.swing.JButton();
        jBseguidores = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPencabezado.setBackground(new java.awt.Color(20, 31, 39));

        jBatras.setText("Atras");
        jBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatrasActionPerformed(evt);
            }
        });

        jLNombre.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(240, 240, 240));
        jLNombre.setText("Alejandro Martinez");

        jLNoTweets.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLNoTweets.setForeground(new java.awt.Color(240, 240, 240));
        jLNoTweets.setText("200 Tweets");

        javax.swing.GroupLayout jPencabezadoLayout = new javax.swing.GroupLayout(jPencabezado);
        jPencabezado.setLayout(jPencabezadoLayout);
        jPencabezadoLayout.setHorizontalGroup(
            jPencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPencabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBatras)
                .addGroup(jPencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPencabezadoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLNoTweets))
                    .addGroup(jPencabezadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLNombre)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPencabezadoLayout.setVerticalGroup(
            jPencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPencabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPencabezadoLayout.createSequentialGroup()
                        .addComponent(jBatras)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPencabezadoLayout.createSequentialGroup()
                        .addComponent(jLNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLNoTweets)
                        .addGap(24, 24, 24))))
        );

        jPcentro.setBackground(new java.awt.Color(20, 31, 39));

        jLabel1.setBackground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("jLabel1");

        jLNombre1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLNombre1.setForeground(new java.awt.Color(240, 240, 240));
        jLNombre1.setText("Alejandro Martinez");

        jBsiguiendo.setText("jButton1");
        jBsiguiendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsiguiendoActionPerformed(evt);
            }
        });

        jBseguidores.setText("jButton2");
        jBseguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseguidoresActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(20, 31, 39));
        jButton3.setForeground(new java.awt.Color(0, 172, 238));
        jButton3.setText("Tweets");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPcentroLayout = new javax.swing.GroupLayout(jPcentro);
        jPcentro.setLayout(jPcentroLayout);
        jPcentroLayout.setHorizontalGroup(
            jPcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcentroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcentroLayout.createSequentialGroup()
                        .addComponent(jBsiguiendo)
                        .addGap(18, 18, 18)
                        .addComponent(jBseguidores))
                    .addComponent(jLNombre1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPcentroLayout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPcentroLayout.setVerticalGroup(
            jPcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLNombre1)
                .addGap(18, 18, 18)
                .addGroup(jPcentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsiguiendo)
                    .addComponent(jBseguidores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jPanel1.setBackground(new java.awt.Color(20, 31, 39));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPencabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPcentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPencabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPcentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBseguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBseguidoresActionPerformed
        new ListaUsuario().setVisible(true);
    }//GEN-LAST:event_jBseguidoresActionPerformed

    private void jBsiguiendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsiguiendoActionPerformed
         new ListaUsuario().setVisible(true);
    }//GEN-LAST:event_jBsiguiendoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBatrasActionPerformed

    
    /*public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaUsuario().setVisible(true);
            }
        });
    }*/
    
   /* public static void main(String args[]){
        new PaginaUsuario("Andrea", );
    }*/
    
    
    public void defineComponents(){
        
        System.out.println("Los datos son "+datosUsuario.get(0));
        
        jBatras.setText("ATRAS");
        jLNombre.setText(""+datosUsuario.get(0));
        jLNombre1.setText(""+datosUsuario.get(0));
        jLNoTweets.setText(""+datosUsuario.get(2)+" Tweets");
        jBseguidores.setText(""+datosUsuario.get(3)+" Seguidores");
        jBsiguiendo.setText(""+datosUsuario.get(4)+" Siguiendo");
        icon = new ImageIcon(fotoUsuario.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icon);
        //this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBatras;
    private javax.swing.JButton jBseguidores;
    private javax.swing.JButton jBsiguiendo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLNoTweets;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNombre1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPcentro;
    public javax.swing.JPanel jPencabezado;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
